# -*- coding: utf-8 -*-
"""Метаданные выходных параметров для расчёта пневмотранспорта ПКН."""

from collections import OrderedDict

GROUPS = OrderedDict({
    'Промежуточные расчетные данные': True,
    'Производительность': True,
    'Аэродинамика и трасса': True,
    'Компрессор': True,
})

OUTPUT_PARAMS = OrderedDict([
 
('unloading_time_sec', {
    'view': True,
    'header': 'Время разгрузки',
    'dimension': 'сек',
    'comment': '',
    'group_name': 'Промежуточные расчетные данные',
    'accuracy': 2,
}),
('system_temp_k', {
    'view': True,
    'header': 'Температура системы',
    'dimension': 'К',
    'comment': '',
    'group_name': 'Промежуточные расчетные данные',
    'accuracy': 2,
}),
('dynamic_viscosity_pa_s', {
    'view': True,
    'header': 'Динамическая вязкость при Тсист.',
    'dimension': 'Па*с',
    'comment': '',
    'group_name': 'Промежуточные расчетные данные',
    'accuracy': 2,
}),
('air_density_kg_m3', {
    'view': True,
    'header': 'Плотность воздуха при Тсист.',
    'dimension': 'кг/м3',
    'comment': '',
    'group_name': 'Промежуточные расчетные данные',
    'accuracy': 2,
}),
('kinematic_viscosity_m2_s', {
    'view': True,
    'header': 'Кинематическая вязкость газа',
    'dimension': 'м2/с',
    'comment': '',
    'group_name': 'Промежуточные расчетные данные',
    'accuracy': 2,
}),
 
 
 ('productivity_unloading_kg_s',
  {'view': True,
   'header': 'Производительность по t разгрузки',
   'dimension': 'кг/сек',
   'comment': '',
   'group_name': 'Производительность',
   'accuracy': 2}),
 ('productivity_cycles_per_hour',
  {'view': True,
   'header': 'Производительность (циклов/час) по t разгрузки',
   'dimension': '',
   'comment': '',
   'group_name': 'Производительность',
   'accuracy': 2}),
 ('productivity_by_cycles_kg_h',
  {'view': True,
   'header': 'Производительность по циклам',
   'dimension': 'кг/ч',
   'comment': '',
   'group_name': 'Производительность',
   'accuracy': 2}),
 ('mass_pump_volume_kg',
  {'view': True,
   'header': 'Массовый объем насоса',
   'dimension': 'кг',
   'comment': '',
   'group_name': 'Производительность',
   'accuracy': 2}),
 ('pump_cycle_count_per_hour',
  {'view': True,
   'header': 'Количество циклов насоса',
   'dimension': 'цикл/ч',
   'comment': '',
   'group_name': 'Производительность',
   'accuracy': 2}),
 ('solid_flow_m3_h',
  {'view': True,
   'header': 'Расход твердого вещества',
   'dimension': 'м3/ч',
   'comment': '',
   'group_name': 'Производительность',
   'accuracy': 2}),
 ('reduced_length_m',
  {'view': True,
   'header': 'Приведенная длина трассы',
   'dimension': 'м',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('settling_velocity_m_s',
  {'view': True,
   'header': 'Скорость витания',
   'dimension': 'м/с',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('archimedes_number',
  {'view': True,
   'header': 'Критерий Архимеда (Ar)',
   'dimension': '',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('reynolds_number_for_settling',
  {'view': True,
   'header': 'Критерий Рейнольдса для скорости витания (Ra)',
   'dimension': '',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('air_flow_m3_min',
  {'view': True,
   'header': 'Расход воздуха',
   'dimension': 'м3/мин',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('calculated_diameter_m',
  {'view': True,
   'header': 'Диаметр расчётн.',
   'dimension': 'м',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('actual_diameter_m',
  {'view': True,
   'header': 'Фактический принятый',
   'dimension': 'м',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('s_for_beta',
  {'view': True,
   'header': 'S для коэф. Бета',
   'dimension': '',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('beta_coefficient',
  {'view': True,
   'header': 'бета по рис.11',
   'dimension': '',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('transport_resistance_bar',
  {'view': True,
   'header': 'Сопротивление транспортировки',
   'dimension': 'бар',
   'comment': '',
   'group_name': 'Аэродинамика и трасса',
   'accuracy': 2}),
 ('compressor_pressure_bar',
  {'view': True,
   'header': 'Давление компрессора',
   'dimension': 'бар',
   'comment': '',
   'group_name': 'Компрессор',
   'accuracy': 2}),
 ('inlet_air_velocity_m_s',
  {'view': True,
   'header': 'Скорость воздуха в начале транспортировки',
   'dimension': 'м/с',
   'comment': '',
   'group_name': 'Компрессор',
   'accuracy': 2})])
