CALC_FUNCTIONS = OrderedDict([
    # === БАЗА: константы/входные/прямые ==='}),'}),
    ('edinica_rashoda_imya', {'fnc': calc_edinica_rashoda_imya, 'cell': 'Excel O5'}),
    ('ploschad_vyhoda_shg_m2', {'fnc': calc_ploschad_vyhoda_shg_m2, 'cell': 'Excel O18'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('skorost_na_vyhode_shg_m_s', {'fnc': calc_skorost_na_vyhode_shg_m_s, 'cell': 'Excel O19'}),
    ('r_reaktivnye_sily_n', {'fnc': calc_r_reaktivnye_sily_n, 'cell': 'Excel O20'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('sreda_2', {'fnc': calc_sreda_2, 'cell': 'Excel O23'}),
    ('rashod_sredy_g_kg_s', {'fnc': calc_rashod_sredy_g_kg_s, 'cell': 'Excel O24'}),
    ('temperatura_sredy_s_2', {'fnc': calc_temperatura_sredy_s_2, 'cell': 'Excel O25'}),
    ('davlenie_na_vhode_v_shg_pi_abs_mpa', {'fnc': calc_davlenie_na_vhode_v_shg_pi_abs_mpa, 'cell': 'Excel O26'}),
    ('gazovaya_postoyannaya_m2_s2_k', {'fnc': calc_gazovaya_postoyannaya_m2_s2_k, 'cell': 'Excel O29'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('molyarnaya_massa_sredy_kg_mol', {'fnc': calc_molyarnaya_massa_sredy_kg_mol, 'cell': 'Excel O6'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('koeffcient_adiabaty', {'fnc': calc_koeffcient_adiabaty, 'cell': 'Excel O31'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('epsilon_1', {'fnc': calc_epsilon_1, 'cell': 'Excel O12'}),
    ('y_1', {'fnc': calc_y_1, 'cell': 'Excel O14'}),
    ('kriticheskaya_skorost_skr_m_s', {'fnc': calc_kriticheskaya_skorost_skr_m_s, 'cell': 'Excel O28'}),
    ('temperatura_k', {'fnc': calc_temperatura_k, 'cell': 'Excel O135'}),
    ('da_vnutrennij_diametr_vyhlopa_iz_korpusa_m', {'fnc': calc_da_vnutrennij_diametr_vyhlopa_iz_korpusa_m, 'cell': 'Excel O139'}),
    ('sa_ploschad_secheniya_shumoglushitelya_m2', {'fnc': calc_sa_ploschad_secheniya_shumoglushitelya_m2, 'cell': 'Excel O136'}),
    ('nezapolnennaya_ploschad_kv_m', {'fnc': calc_nezapolnennaya_ploschad_kv_m, 'cell': 'Excel O140'}),
    ('gidravlicheskij_diametr_m', {'fnc': calc_gidravlicheskij_diametr_m, 'cell': 'Excel O141'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('g_rashod_sredy_kg_s_2', {'fnc': calc_g_rashod_sredy_kg_s_2, 'cell': 'Excel O274'}),
    ('k_koefficient_adiabaty', {'fnc': calc_k_koefficient_adiabaty, 'cell': 'Excel O275'}),
    ('r_individualnaya_gazovaya_postoyannaya_m2s2_k', {'fnc': calc_r_individualnaya_gazovaya_postoyannaya_m2s2_k, 'cell': 'Excel O276'}),
    ('t_temperatura_sredy_k', {'fnc': calc_t_temperatura_sredy_k, 'cell': 'Excel O277'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('pat_atmosfernoe_davlenie_pa_2', {'fnc': calc_pat_atmosfernoe_davlenie_pa_2, 'cell': 'Excel O278'}),
    ('d_vnutrennij_diametr_korpusa_stupeni_zvukopogloscheniya_m',
     calc_d_vnutrennij_diametr_korpusa_stupeni_zvukopogloscheniya_m, 'cell': 'Excel O279'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('hk_osevoe_rasstoyanie_ot_vyhodnogo_secheniya_korpusa_do_kryshki_m',
     calc_hk_osevoe_rasstoyanie_ot_vyhodnogo_secheniya_korpusa_do_kryshki_m, 'cell': 'Excel O281'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('sk_ploschad_vyhodnogo_secheniya_kanala_korpusa_do_kryshki_m2',
     calc_sk_ploschad_vyhodnogo_secheniya_kanala_korpusa_do_kryshki_m2, 'cell': 'Excel O282'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('da_vnutrennij_diametr_vyhlopa_m', {'fnc': calc_da_vnutrennij_diametr_vyhlopa_m, 'cell': 'Excel O280'}),
    ('sa', {'fnc': calc_sa, 'cell': 'Excel O283'}),
    ('pk_izbytochnoe_davlenie_pod_kryshkoj_pa_2', {'fnc': calc_pk_izbytochnoe_davlenie_pod_kryshkoj_pa_2, 'cell': 'Excel O284'}),
    ('pk_izbytochnoe_davlenie_pod_kryshkoj_pa', {'fnc': calc_pk_izbytochnoe_davlenie_pod_kryshkoj_pa, 'cell': 'Excel O150'}),
    ('izbytochnoe_davlenie_pod_kryshkoj_ne_mozhet_prevyshat_15000_pa', {'fnc':
     calc_izbytochnoe_davlenie_pod_kryshkoj_ne_mozhet_prevyshat_15000_pa, 'cell': 'Excel O154'}),
    ('pa_izbytochnoe_davlenie_na_vyhode_iz_korpusa_za_stupenyu_zvukopogloscheniya_pa_2',{'fnc':
     calc_pa_izbytochnoe_davlenie_na_vyhode_iz_korpusa_za_stupenyu_zvukopogloscheniya_pa_2, 'cell': 'Excel O285'}),
    ('pa_izbytochnoe_davlenie_na_vyhode_iz_korpusa_za_stupenyu_zvukopogloscheniya_pa',{'fnc':
     calc_pa_izbytochnoe_davlenie_na_vyhode_iz_korpusa_za_stupenyu_zvukopogloscheniya_pa, 'cell': 'Excel O151'}),
    ('izbytochnoe_davlenie_na_vyhode_iz_korpusa_za_stupenyu_zvukopogloscheniya_ne_mozhet_prevyshat_15000_pa',{'fnc':
     calc_izbytochnoe_davlenie_na_vyhode_iz_korpusa_za_stupenyu_zvukopogloscheniya_ne_mozhet_prevyshat_15000_pa, 'cell':'Excel O155'}),
    ('pa_absolyutnoe_davlenie_za_stupenyu_zvukopogloscheniya_pa_2',{'fnc':
     calc_pa_absolyutnoe_davlenie_za_stupenyu_zvukopogloscheniya_pa_2, 'cell': 'Excel O286'}),
    ('pa_absolyutnoe_davlenie_za_stupenyu_zvukopogloscheniya_pa',{'fnc':
     calc_pa_absolyutnoe_davlenie_za_stupenyu_zvukopogloscheniya_pa, 'cell': 'Excel O152'}),
    ('v_skorost_mezhdu_plastinami_m_s', {'fnc': calc_v_skorost_mezhdu_plastinami_m_s, 'cell': 'Excel O10'}),
    ('k', {'fnc': calc_k, 'cell': 'Excel O13'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('kolichestvo_stupenej_drosselirovaniya_j', {'fnc': calc_kolichestvo_stupenej_drosselirovaniya_j, 'cell': 'Excel O34'}),
    ('maksimalnoe_kolichestvo_otverstij_kmah_v_drosselnoj_reshetke_sht', {'fnc': calc_maksimalnoe_kolichestvo_otverstij_kmah_v_drosselnoj_reshetke_sht, 'cell': 'Excel O35'}),
    ('stupeni_n1', {'fnc': calc_stupeni_n1, 'cell': 'Excel O45'}),
    ('stupeni_n2', {'fnc': calc_stupeni_n2, 'cell': 'Excel O49'}),
    ('stupeni_n3', {'fnc': calc_stupeni_n3, 'cell': 'Excel O53'}),
    ('stupeni_n4', {'fnc': calc_stupeni_n4, 'cell': 'Excel O57'}),
    ('stupeni_n5', {'fnc': calc_stupeni_n5, 'cell': 'Excel O61'}),
    ('stupeni_n6', {'fnc': calc_stupeni_n6, 'cell': 'Excel O65'}),
    ('stupeni_n7', {'fnc': calc_stupeni_n7, 'cell': 'Excel O69'}),
    ('stupeni_n8', {'fnc': calc_stupeni_n8, 'cell': 'Excel O73'}),
    ('stupeni_n9', {'fnc': calc_stupeni_n9, 'cell': 'Excel O77'}),
    ('stupeni_n10', {'fnc': calc_stupeni_n10, 'cell': 'Excel O81'}),
    ('stupeni_n1_2', {'fnc': calc_stupeni_n1_2, 'cell': 'Excel O90'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('stupeni_n2_2', {'fnc': calc_stupeni_n2_2, 'cell': 'Excel O94'}),
    ('stupeni_n3_2', {'fnc': calc_stupeni_n3_2, 'cell': 'Excel O98'}),
    ('stupeni_n4_2', {'fnc': calc_stupeni_n4_2, 'cell': 'Excel O102'}),
    ('stupeni_n5_2', {'fnc': calc_stupeni_n5_2, 'cell': 'Excel O106'}),
    ('stupeni_n6_2', {'fnc': calc_stupeni_n6_2, 'cell': 'Excel O110'}),
    ('stupeni_n7_2', {'fnc': calc_stupeni_n7_2, 'cell': 'Excel O114'}),
    ('stupeni_n8_2', {'fnc': calc_stupeni_n8_2, 'cell': 'Excel O118'}),
    ('stupeni_n9_2', {'fnc': calc_stupeni_n9_2, 'cell': 'Excel O122'}),
    ('stupeni_n10_2', {'fnc': calc_stupeni_n10_2, 'cell': 'Excel O126'}),
    ('plotnost_sredy_kg_m3', {'fnc': calc_plotnost_sredy_kg_m3, 'cell': 'Excel O7'}),
    ('skorost_para_iz_truby_m_s', {'fnc': calc_skorost_para_iz_truby_m_s, 'cell': 'Excel O8'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('perimetr_m', {'fnc': calc_perimetr_m, 'cell': 'Excel O137'}),
    ('sk_ploschad_vyhodnogo_secheniya_korpusa_do_kryshki_kv_m', {'fnc': calc_sk_ploschad_vyhodnogo_secheniya_korpusa_do_kryshki_kv_m, 'cell': 'Excel O138'}),
    # === ПРОМЕЖУТОЧНЫЕ ===
    ('plotnost_rho_po_rashodu_i_geometrii', {'fnc': calc_plotnost_rho_po_rashodu_i_geometrii, 'cell': 'Excel O11'}),
    ('otnositelnaya_ploschad', {'fnc': calc_otnositelnaya_ploschad, 'cell': 'Excel O142'}),
    ('kriticheskij_perepad_davlenij', {'fnc': calc_kriticheskij_perepad_davlenij, 'cell': 'Excel O144'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('stupeni_n0', {'fnc': calc_stupeni_n0, 'cell': 'Excel O173'}),
    ('y_n0', {'fnc': calc_y_n0, 'cell': 'Excel O175'}),
    ('perepad_davlenij_n0', {'fnc': calc_perepad_davlenij_n0, 'cell': 'Excel O176'}),
    ('n0', {'fnc': calc_n0, 'cell': 'Excel O177'}),
    ('n0_2', {'fnc': calc_n0_2, 'cell': 'Excel O178'}),
    ('n0_3', {'fnc': calc_n0_3, 'cell': 'Excel O179'}),
    ('stupeni_n1_3', {'fnc': calc_stupeni_n1_3, 'cell': 'Excel O180'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('stupeni_n2_3', {'fnc': calc_stupeni_n2_3, 'cell': 'Excel O187'}),
    ('stupeni_n3_3', {'fnc': calc_stupeni_n3_3, 'cell': 'Excel O194'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('stupeni_n4_3', {'fnc': calc_stupeni_n4_3, 'cell': 'Excel O201'}),
    ('stupeni_n5_3', {'fnc': calc_stupeni_n5_3, 'cell': 'Excel O208'}),
    ('stupeni_n6_3', {'fnc': calc_stupeni_n6_3, 'cell': 'Excel O215'}),
    ('stupeni_n7_3', {'fnc': calc_stupeni_n7_3, 'cell': 'Excel O222'}),
    ('stupeni_n8_3', {'fnc': calc_stupeni_n8_3, 'cell': 'Excel O229'}),
    ('stupeni_n9_3', {'fnc': calc_stupeni_n9_3, 'cell': 'Excel O236'}),
    ('stupeni_n10_3', {'fnc': calc_stupeni_n10_3, 'cell': 'Excel O243'}),
    ('obtekateli', {'fnc': calc_obtekateli, 'cell': 'Excel O253'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('r_gazovaya_postoyannaya_m2s2_k', {'fnc': calc_r_gazovaya_postoyannaya_m2s2_k, 'cell': 'Excel O254'}),
    ('k_pokazatel_adiabaty', {'fnc': calc_k_pokazatel_adiabaty, 'cell': 'Excel O255'}),
    ('t_absolyutnaya_temperatura_pered_glushitelem_k', {'fnc': calc_t_absolyutnaya_temperatura_pered_glushitelem_k, 'cell': 'Excel O256'}),
    ('g_rashod_sredy_kg_s', {'fnc': calc_g_rashod_sredy_kg_s, 'cell': 'Excel O257'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('d_vnutrennij_diametr_shg_m', {'fnc': calc_d_vnutrennij_diametr_shg_m, 'cell': 'Excel O258'}),
    ('pat_atmosfernoe_davlenie_pa', {'fnc': calc_pat_atmosfernoe_davlenie_pa, 'cell': 'Excel O259'}),
    ('l_dlina_kanalov_m', {'fnc': calc_l_dlina_kanalov_m, 'cell': 'Excel O263'}),
    ('pa_pa', {'fnc': calc_pa_pa, 'cell': 'Excel O265'}),
    # === ФИНАЛ ==='}),
    ('ptr_pa', {'fnc': calc_ptr_pa, 'cell': 'Excel O266'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('plotnost_rho_po_idealnomu_gazu', {'fnc': calc_plotnost_rho_po_idealnomu_gazu, 'cell': 'Excel O270'}),
    ('pk', {'fnc': calc_pk, 'cell': 'Excel O290'}),
    ('wa_skorost_na_vyhode_iz_korpusa_m_s_2', {'fnc': calc_wa_skorost_na_vyhode_iz_korpusa_m_s_2, 'cell': 'Excel O291'}),
    ('wa_skorost_na_vyhode_iz_korpusa_m_s', {'fnc': calc_wa_skorost_na_vyhode_iz_korpusa_m_s, 'cell': 'Excel O161'}),
    ('wk_skorost_na_vyhlope_v_atmosferu_m_s_2', {'fnc': calc_wk_skorost_na_vyhlope_v_atmosferu_m_s_2, 'cell': 'Excel O292'}),
    ('wk_skorost_na_vyhlope_v_atmosferu_m_s', {'fnc': calc_wk_skorost_na_vyhlope_v_atmosferu_m_s, 'cell': 'Excel O162'}),
    ('ma_chislo_maha_na_vyhode_iz_korpusa_2', {'fnc': calc_ma_chislo_maha_na_vyhode_iz_korpusa_2, 'cell': 'Excel O293'}),
    ('ma_chislo_maha_na_vyhode_iz_korpusa', {'fnc': calc_ma_chislo_maha_na_vyhode_iz_korpusa, 'cell': 'Excel O163'}),
    ('mk_chislo_maha_na_vyhlope_v_atmosferu_2', {'fnc': calc_mk_chislo_maha_na_vyhlope_v_atmosferu_2, 'cell': 'Excel O294'}),
    ('mk_chislo_maha_na_vyhlope_v_atmosferu', {'fnc': calc_mk_chislo_maha_na_vyhlope_v_atmosferu, 'cell': 'Excel O164'}),
    ('k_ma', {'fnc': calc_k_ma, 'cell': 'Excel O295'}),
    ('k_mk', {'fnc': calc_k_mk, 'cell': 'Excel O296'}),
    ('wa_moschnost_shuma_na_vyhode_iz_korpusa_vt', {'fnc': calc_wa_moschnost_shuma_na_vyhode_iz_korpusa_vt, 'cell': 'Excel O297'}),
    ('wk_moschnost_shuma_na_vyhode_iz_pod_kryshki_vt', {'fnc': calc_wk_moschnost_shuma_na_vyhode_iz_pod_kryshki_vt, 'cell': 'Excel O298'}),
    ('lwa_uzm_generiruemyj_istecheniem_iz_korpusa_db', {'fnc': calc_lwa_uzm_generiruemyj_istecheniem_iz_korpusa_db, 'cell': 'Excel O299'}),
    ('lwk_uzm_generiruemyj_istecheniem_iz_pod_kryshki_db', {'fnc': calc_lwk_uzm_generiruemyj_istecheniem_iz_pod_kryshki_db, 'cell': 'Excel O300'}),
    ('dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_bokovom_vyhlope_kn_2', {'fnc': calc_dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_bokovom_vyhlope_kn_2, 'cell': 'Excel O306'}),
    ('dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_bokovom_vyhlope_kn', {'fnc': calc_dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_bokovom_vyhlope_kn, 'cell': 'Excel O168'}),
    ('dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_osevom_vyhlope_kn_2', {'fnc': calc_dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_osevom_vyhlope_kn_2, 'cell': 'Excel O307'}),
    ('dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_osevom_vyhlope_kn', {'fnc': calc_dinamicheskaya_nagruzka_na_zaschitnuyu_kryshku_pri_osevom_vyhlope_kn, 'cell': 'Excel O169'}),
    # === БАЗА: константы/входные/прямые ==='}),
    ('r_vnutrennij_radius_m_n1', {'fnc': calc_r_vnutrennij_radius_m_n1, 'cell': 'Excel O311'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('r_naruzhnyj_radius_m_n1', {'fnc': calc_r_naruzhnyj_radius_m_n1, 'cell': 'Excel O312'}),
    ('dh_gidravlicheskij_diametr_m_n1', {'fnc': calc_dh_gidravlicheskij_diametr_m_n1, 'cell': 'Excel O313'}),
    ('d_shirina_kanala_m_n1', {'fnc': calc_d_shirina_kanala_m_n1, 'cell': 'Excel O314'}),
    ('f_dh_0_5_n1', {'fnc': calc_f_dh_0_5_n1, 'cell': 'Excel O316'}),
    ('f_ploschad_kanala_m2_n1', {'fnc': calc_f_ploschad_kanala_m2_n1, 'cell': 'Excel O315'}),
    ('h_srednyaya_tolschina_plastin_m_n1', {'fnc': calc_h_srednyaya_tolschina_plastin_m_n1, 'cell': 'Excel O317'}),
    ('pd_skorostnoj_napor_na_vyhode_pa_n1', {'fnc': calc_pd_skorostnoj_napor_na_vyhode_pa_n1, 'cell': 'Excel O318'}),
    ('g_rashod_v_kanale_kg_s_n1', {'fnc': calc_g_rashod_v_kanale_kg_s_n1, 'cell': 'Excel O319'}),
    ('w_skorost_v_kanale_m_s_n1', {'fnc': calc_w_skorost_v_kanale_m_s_n1, 'cell': 'Excel O320'}),
    ('m_chislo_maha_v_kanale_n1', {'fnc': calc_m_chislo_maha_v_kanale_n1, 'cell': 'Excel O321'}),
    ('k_m_n1', {'fnc': calc_k_m_n1, 'cell': 'Excel O322'}),
    ('ds_n1', {'fnc': calc_ds_n1, 'cell': 'Excel O323'}),
    ('ws_moschnost_shuma_na_vyhode_kanala_vt_n1', {'fnc': calc_ws_moschnost_shuma_na_vyhode_kanala_vt_n1, 'cell': 'Excel O324'}),
    ('lws_n1', {'fnc': calc_lws_n1, 'cell': 'Excel O325'}),
    ('r_vnutrennij_radius_m_n2', {'fnc': calc_r_vnutrennij_radius_m_n2, 'cell': 'Excel O326'}),
    ('r_naruzhnyj_radius_m_n2', {'fnc': calc_r_naruzhnyj_radius_m_n2, 'cell': 'Excel O327'}),
    ('dh_gidravlicheskij_diametr_m_n2', {'fnc': calc_dh_gidravlicheskij_diametr_m_n2, 'cell': 'Excel O328'}),
    ('d_shirina_kanala_m_n2', {'fnc': calc_d_shirina_kanala_m_n2, 'cell': 'Excel O329'}),
    ('f_ploschad_kanala_m2_n2', {'fnc': calc_f_ploschad_kanala_m2_n2, 'cell': 'Excel O330'}),
    ('f_dh_0_5_n2', {'fnc': calc_f_dh_0_5_n2, 'cell': 'Excel O331'}),
    ('h_srednyaya_tolschina_plastin_m_n2', {'fnc': calc_h_srednyaya_tolschina_plastin_m_n2, 'cell': 'Excel O332'}),
    ('pd_skorostnoj_napor_na_vyhode_pa_n2', {'fnc': calc_pd_skorostnoj_napor_na_vyhode_pa_n2, 'cell': 'Excel O333'}),
    ('g_rashod_v_kanale_kg_s_n2', {'fnc': calc_g_rashod_v_kanale_kg_s_n2, 'cell': 'Excel O334'}),
    ('w_skorost_v_kanale_m_s_n2', {'fnc': calc_w_skorost_v_kanale_m_s_n2, 'cell': 'Excel O335'}),
    ('m_chislo_maha_v_kanale_n2', {'fnc': calc_m_chislo_maha_v_kanale_n2, 'cell': 'Excel O336'}),
    ('k_m_n2', {'fnc': calc_k_m_n2, 'cell': 'Excel O337'}),
    ('ds_n2', {'fnc': calc_ds_n2, 'cell': 'Excel O338'}),
    ('ws_moschnost_shuma_na_vyhode_kanala_vt_n2', {'fnc': calc_ws_moschnost_shuma_na_vyhode_kanala_vt_n2, 'cell': 'Excel O339'}),
    ('lws_n2', {'fnc': calc_lws_n2, 'cell': 'Excel O340'}),
    ('r_vnutrennij_radius_m_n3', {'fnc': calc_r_vnutrennij_radius_m_n3, 'cell': 'Excel O341'}),
    ('r_naruzhnyj_radius_m_n3', {'fnc': calc_r_naruzhnyj_radius_m_n3, 'cell': 'Excel O342'}),
    ('dh_gidravlicheskij_diametr_m_n3', {'fnc': calc_dh_gidravlicheskij_diametr_m_n3, 'cell': 'Excel O343'}),
    ('d_shirina_kanala_m_n3', {'fnc': calc_d_shirina_kanala_m_n3, 'cell': 'Excel O344'}),
    ('f_ploschad_kanala_m2_n3', {'fnc': calc_f_ploschad_kanala_m2_n3, 'cell': 'Excel O345'}),
    ('f_dh_0_5_n3', {'fnc': calc_f_dh_0_5_n3, 'cell': 'Excel O346'}),
    ('h_srednyaya_tolschina_plastin_m_n3', {'fnc': calc_h_srednyaya_tolschina_plastin_m_n3, 'cell': 'Excel O347'}),
    ('pd_skorostnoj_napor_na_vyhode_pa_n3', {'fnc': calc_pd_skorostnoj_napor_na_vyhode_pa_n3, 'cell': 'Excel O348'}),
    ('g_rashod_v_kanale_kg_s_n3', {'fnc': calc_g_rashod_v_kanale_kg_s_n3, 'cell': 'Excel O349'}),
    ('w_skorost_v_kanale_m_s_n3', {'fnc': calc_w_skorost_v_kanale_m_s_n3, 'cell': 'Excel O350'}),
    ('m_chislo_maha_v_kanale_n3', {'fnc': calc_m_chislo_maha_v_kanale_n3, 'cell': 'Excel O351'}),
    ('k_m_n3', {'fnc': calc_k_m_n3, 'cell': 'Excel O352'}),
    ('ds_n3', {'fnc': calc_ds_n3, 'cell': 'Excel O353'}),
    ('ws_moschnost_shuma_na_vyhode_kanala_vt_n3', {'fnc': calc_ws_moschnost_shuma_na_vyhode_kanala_vt_n3, 'cell': 'Excel O354'}),
    ('lws_n3', {'fnc': calc_lws_n3, 'cell': 'Excel O355'}),
    ('r_vnutrennij_radius_m_n4', {'fnc': calc_r_vnutrennij_radius_m_n4, 'cell': 'Excel O356'}),
    ('r_naruzhnyj_radius_m_n4', {'fnc': calc_r_naruzhnyj_radius_m_n4, 'cell': 'Excel O357'}),
    ('dh_gidravlicheskij_diametr_m_n4', {'fnc': calc_dh_gidravlicheskij_diametr_m_n4, 'cell': 'Excel O358'}),
    ('d_shirina_kanala_m_n4', {'fnc': calc_d_shirina_kanala_m_n4, 'cell': 'Excel O359'}),
    ('f_ploschad_kanala_m2_n4', {'fnc': calc_f_ploschad_kanala_m2_n4, 'cell': 'Excel O360'}),
    ('f_dh_0_5_n4', {'fnc': calc_f_dh_0_5_n4, 'cell': 'Excel O361'}),
    ('h_srednyaya_tolschina_plastin_m_n4', {'fnc': calc_h_srednyaya_tolschina_plastin_m_n4, 'cell': 'Excel O362'}),
    ('pd_skorostnoj_napor_na_vyhode_pa_n4', {'fnc': calc_pd_skorostnoj_napor_na_vyhode_pa_n4, 'cell': 'Excel O363'}),
    ('g_rashod_v_kanale_kg_s_n4', {'fnc': calc_g_rashod_v_kanale_kg_s_n4, 'cell': 'Excel O364'}),
    ('w_skorost_v_kanale_m_s_n4', {'fnc': calc_w_skorost_v_kanale_m_s_n4, 'cell': 'Excel O365'}),
    ('m_chislo_maha_v_kanale_n4', {'fnc': calc_m_chislo_maha_v_kanale_n4, 'cell': 'Excel O366'}),
    ('k_m_n4', {'fnc': calc_k_m_n4, 'cell': 'Excel O367'}),
    ('ds_n4', {'fnc': calc_ds_n4, 'cell': 'Excel O368'}),
    ('ws_moschnost_shuma_na_vyhode_kanala_vt_n4', {'fnc': calc_ws_moschnost_shuma_na_vyhode_kanala_vt_n4, 'cell': 'Excel O369'}),
    ('lws_n4', {'fnc': calc_lws_n4, 'cell': 'Excel O370'}),
    ('r_vnutrennij_radius_m_n5', {'fnc': calc_r_vnutrennij_radius_m_n5, 'cell': 'Excel O371'}),
    ('r_naruzhnyj_radius_m_n5', {'fnc': calc_r_naruzhnyj_radius_m_n5, 'cell': 'Excel O372'}),
    ('dh_gidravlicheskij_diametr_m_n5', {'fnc': calc_dh_gidravlicheskij_diametr_m_n5, 'cell': 'Excel O373'}),
    ('d_shirina_kanala_m_n5', {'fnc': calc_d_shirina_kanala_m_n5, 'cell': 'Excel O374'}),
    ('f_ploschad_kanala_m2_n5', {'fnc': calc_f_ploschad_kanala_m2_n5, 'cell': 'Excel O375'}),
    ('f_dh_0_5_n5', {'fnc': calc_f_dh_0_5_n5, 'cell': 'Excel O376'}),
    ('h_srednyaya_tolschina_plastin_m_n5', {'fnc': calc_h_srednyaya_tolschina_plastin_m_n5, 'cell': 'Excel O377'}),
    ('pd_skorostnoj_napor_na_vyhode_pa_n5', {'fnc': calc_pd_skorostnoj_napor_na_vyhode_pa_n5, 'cell': 'Excel O378'}),
    ('g_rashod_v_kanale_kg_s_n5', {'fnc': calc_g_rashod_v_kanale_kg_s_n5, 'cell': 'Excel O379'}),
    ('w_skorost_v_kanale_m_s_n5', {'fnc': calc_w_skorost_v_kanale_m_s_n5, 'cell': 'Excel O380'}),
    ('m_chislo_maha_v_kanale_n5', {'fnc': calc_m_chislo_maha_v_kanale_n5, 'cell': 'Excel O381'}),
    ('k_m_n5', {'fnc': calc_k_m_n5, 'cell': 'Excel O382'}),
    ('ds_n5', {'fnc': calc_ds_n5, 'cell': 'Excel O383'}),
    ('ws_moschnost_shuma_na_vyhode_kanala_vt_n5', {'fnc': calc_ws_moschnost_shuma_na_vyhode_kanala_vt_n5, 'cell': 'Excel O384'}),
    ('lws_n5', {'fnc': calc_lws_n5, 'cell': 'Excel O385'}),
    ('r_vnutrennij_radius_m_n6', {'fnc': calc_r_vnutrennij_radius_m_n6, 'cell': 'Excel O386'}),
    ('r_naruzhnyj_radius_m_n6', {'fnc': calc_r_naruzhnyj_radius_m_n6, 'cell': 'Excel O387'}),
    ('dh_gidravlicheskij_diametr_m_n6', {'fnc': calc_dh_gidravlicheskij_diametr_m_n6, 'cell': 'Excel O388'}),
    ('d_shirina_kanala_m_n6', {'fnc': calc_d_shirina_kanala_m_n6, 'cell': 'Excel O389'}),
    ('f_ploschad_kanala_m2_n6', {'fnc': calc_f_ploschad_kanala_m2_n6, 'cell': 'Excel O390'}),
    # === ФИНАЛ ==='}),
    ('ss_summarnaya_ploschad_vseh_kanalov_m2', {'fnc': calc_ss_summarnaya_ploschad_vseh_kanalov_m2, 'cell': 'Excel O260'}),
    # === ПРОМЕЖУТОЧНЫЕ ==='}),
    ('f_otnositelnaya_ploschad', {'fnc': calc_f_otnositelnaya_ploschad, 'cell': 'Excel O262'}),
    ('pi3_davlenie_pered_stupenyu_zvukopogloscheniya_pa_2', {'fnc': calc_pi3_davlenie_pered_stupenyu_zvukopogloscheniya_pa_2, 'cell': 'Excel O267'}),
    ('pi3_davlenie_pered_stupenyu_zvukopogloscheniya_pa', {'fnc': calc_pi3_davlenie_pered_stupenyu_zvukopogloscheniya_pa, 'cell': 'Excel O153'}),
    ('davlenie_na_vyhode_iz_shg_pe_mpa', {'fnc': calc_davlenie_na_vyhode_iz_shg_pe_mpa, 'cell': 'Excel O27'}),
    ('znachenie_p_drosselnogo_bloka', {'fnc': calc_znachenie_p_drosselnogo_bloka, 'cell': 'Excel O30'}),
    ('maksimalnyj_gradient_skorosti_wmax', {'fnc': calc_maksimalnyj_gradient_skorosti_wmax, 'cell': 'Excel O39'}),
    ('rekomenduemoe_nachalnoe_znachenie_w', {'fnc': calc_rekomenduemoe_nachalnoe_znachenie_w, 'cell': 'Excel O40'}),
    ('gradient_skorosti_w', {'fnc': calc_gradient_skorosti_w, 'cell': 'Excel O38'}),
    ('otnositelnyj_perepad_davleniya_na_poslednej_reshetke', {'fnc': calc_otnositelnyj_perepad_davleniya_na_poslednej_reshetke, 'cell': 'Excel O42'}),
    ('perepad_davlenij_n10', {'fnc': calc_perepad_davlenij_n10, 'cell': 'Excel O82'}),
    ('perepad_davlenij_n9', {'fnc': calc_perepad_davlenij_n9, 'cell': 'Excel O78'}),
    ('perepad_davlenij_n8', {'fnc': calc_perepad_davlenij_n8, 'cell': 'Excel O74'}),
    ('perepad_davlenij_n7', {'fnc': calc_perepad_davlenij_n7, 'cell': 'Excel O70'}),
    ('perepad_davlenij_n6', {'fnc': calc_perepad_davlenij_n6, 'cell': 'Excel O66'}),
    ('perepad_davlenij_n5', {'fnc': calc_perepad_davlenij_n5, 'cell': 'Excel O62'}),
    ('perepad_davlenij_n4', {'fnc': calc_perepad_davlenij_n4, 'cell': 'Excel O58'}),
    ('perepad_davlenij_n3', {'fnc': calc_perepad_davlenij_n3, 'cell': 'Excel O54'}),
    ('perepad_davlenij_n2', {'fnc': calc_perepad_davlenij_n2, 'cell': 'Excel O50'}),
    ('perepad_davlenij_n1', {'fnc': calc_perepad_davlenij_n1, 'cell': 'Excel O46'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n1', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n1, 'cell': 'Excel O47'}),
    ('oblast_n1', {'fnc': calc_oblast_n1, 'cell': 'Excel O48'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n2', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n2, 'cell': 'Excel O51'}),
    ('oblast_n2', {'fnc': calc_oblast_n2, 'cell': 'Excel O52'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n3', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n3, 'cell': 'Excel O55'}),
    ('oblast_n3', {'fnc': calc_oblast_n3, 'cell': 'Excel O56'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n4', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n4, 'cell': 'Excel O59'}),
    ('oblast_n4', {'fnc': calc_oblast_n4, 'cell': 'Excel O60'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n5', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n5, 'cell': 'Excel O63'}),
    ('oblast_n5', {'fnc': calc_oblast_n5, 'cell': 'Excel O64'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n6', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n6, 'cell': 'Excel O67'}),
    ('oblast_n6', {'fnc': calc_oblast_n6, 'cell': 'Excel O68'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n7', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n7, 'cell': 'Excel O71'}),
    ('oblast_n7', {'fnc': calc_oblast_n7, 'cell': 'Excel O72'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n8', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n8, 'cell': 'Excel O75'}),
    ('oblast_n8', {'fnc': calc_oblast_n8, 'cell': 'Excel O76'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n9', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n9, 'cell': 'Excel O79'}),
    ('oblast_n9', {'fnc': calc_oblast_n9, 'cell': 'Excel O80'}),
    ('gazodinamicheskaya_funkciya_rashoda_q_n10', {'fnc': calc_gazodinamicheskaya_funkciya_rashoda_q_n10, 'cell': 'Excel O83'}),
    ('oblast_n10', {'fnc': calc_oblast_n10, 'cell': 'Excel O84'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n1', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n1, 'cell': 'Excel O92'}),
    ('diametry_otverstij_mm_n1', {'fnc': calc_diametry_otverstij_mm_n1, 'cell': 'Excel O91'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n1', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n1, 'cell': 'Excel O93'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n2', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n2, 'cell': 'Excel O96'}),
    ('diametry_otverstij_mm_n2', {'fnc': calc_diametry_otverstij_mm_n2, 'cell': 'Excel O95'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n2', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n2, 'cell': 'Excel O97'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n3', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n3, 'cell': 'Excel O100'}),
    ('diametry_otverstij_mm_n3', {'fnc': calc_diametry_otverstij_mm_n3, 'cell': 'Excel O99'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n3', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n3, 'cell': 'Excel O101'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n4', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n4, 'cell': 'Excel O104'}),
    ('diametry_otverstij_mm_n4', {'fnc': calc_diametry_otverstij_mm_n4, 'cell': 'Excel O103'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n4', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n4, 'cell': 'Excel O105'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n5', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n5, 'cell': 'Excel O108'}),
    ('diametry_otverstij_mm_n5', {'fnc': calc_diametry_otverstij_mm_n5, 'cell': 'Excel O107'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n5', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n5, 'cell': 'Excel O109'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n6', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n6, 'cell': 'Excel O112'}),
    ('diametry_otverstij_mm_n6', {'fnc': calc_diametry_otverstij_mm_n6, 'cell': 'Excel O111'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n6', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n6, 'cell': 'Excel O113'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n7', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n7, 'cell': 'Excel O116'}),
    ('diametry_otverstij_mm_n7', {'fnc': calc_diametry_otverstij_mm_n7, 'cell': 'Excel O115'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n7', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n7, 'cell': 'Excel O117'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n8', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n8, 'cell': 'Excel O120'}),
    ('diametry_otverstij_mm_n8', {'fnc': calc_diametry_otverstij_mm_n8, 'cell': 'Excel O119'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n8', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n8, 'cell': 'Excel O121'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n9', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n9, 'cell': 'Excel O124'}),
    ('diametry_otverstij_mm_n9', {'fnc': calc_diametry_otverstij_mm_n9, 'cell': 'Excel O123'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n9', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n9, 'cell': 'Excel O125'}),
    ('prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n10', {'fnc': calc_prohodnye_ploschadi_drosselnyh_reshetok_fi_mm2_n10, 'cell': 'Excel O128'}),
    ('diametry_otverstij_mm_n10', {'fnc': calc_diametry_otverstij_mm_n10, 'cell': 'Excel O127'}),
    ('minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n10', {'fnc': calc_minimalnye_ploschadi_drosselnyh_reshetok_trebuemye_dlya_razmescheniya_otverstij_ftr_mm2_n10, 'cell': 'Excel O129'}),
    ('davlenie_za_reshetkami_mpa_n10', {'fnc': calc_davlenie_za_reshetkami_mpa_n10, 'cell': 'Excel O244'}),
    ('y_n10', {'fnc': calc_y_n10, 'cell': 'Excel O245'}),
    ('n10', {'fnc': calc_n10, 'cell': 'Excel O247'}),
    ('n10_2', {'fnc': calc_n10_2, 'cell': 'Excel O248'}),
    ('n10_3', {'fnc': calc_n10_3, 'cell': 'Excel O249'}),
    ('perepad_davlenij_n10_2', {'fnc': calc_perepad_davlenij_n10_2, 'cell': 'Excel O246'}),
    ('davlenie_za_reshetkami_mpa_n9', {'fnc': calc_davlenie_za_reshetkami_mpa_n9, 'cell': 'Excel O237'}),
    ('y_n9', {'fnc': calc_y_n9, 'cell': 'Excel O238'}),
    ('n9', {'fnc': calc_n9, 'cell': 'Excel O240'}),
    ('n9_2', {'fnc': calc_n9_2, 'cell': 'Excel O241'}),
    ('n9_3', {'fnc': calc_n9_3, 'cell': 'Excel O242'}),
    ('perepad_davlenij_n9_2', {'fnc': calc_perepad_davlenij_n9_2, 'cell': 'Excel O239'}),
    ('davlenie_za_reshetkami_mpa_n8', {'fnc': calc_davlenie_za_reshetkami_mpa_n8, 'cell': 'Excel O230'}),
    ('y_n8', {'fnc': calc_y_n8, 'cell': 'Excel O231'}),
    ('n8', {'fnc': calc_n8, 'cell': 'Excel O233'}),
    ('n8_2', {'fnc': calc_n8_2, 'cell': 'Excel O234'}),
    ('n8_3', {'fnc': calc_n8_3, 'cell': 'Excel O235'}),
    ('perepad_davlenij_n8_2', {'fnc': calc_perepad_davlenij_n8_2, 'cell': 'Excel O232'}),
    ('davlenie_za_reshetkami_mpa_n7', {'fnc': calc_davlenie_za_reshetkami_mpa_n7, 'cell': 'Excel O223'}),
    ('y_n7', {'fnc': calc_y_n7, 'cell': 'Excel O224'}),
    ('n7', {'fnc': calc_n7, 'cell': 'Excel O226'}),
    ('n7_2', {'fnc': calc_n7_2, 'cell': 'Excel O227'}),
    ('n7_3', {'fnc': calc_n7_3, 'cell': 'Excel O228'}),
    ('perepad_davlenij_n7_2', {'fnc': calc_perepad_davlenij_n7_2, 'cell': 'Excel O225'}),
    ('davlenie_za_reshetkami_mpa_n6', {'fnc': calc_davlenie_za_reshetkami_mpa_n6, 'cell': 'Excel O216'}),
    ('y_n6', {'fnc': calc_y_n6, 'cell': 'Excel O217'}),
    ('n6', {'fnc': calc_n6, 'cell': 'Excel O219'}),
    ('n6_2', {'fnc': calc_n6_2, 'cell': 'Excel O220'}),
    ('n6_3', {'fnc': calc_n6_3, 'cell': 'Excel O221'}),
    ('perepad_davlenij_n6_2', {'fnc': calc_perepad_davlenij_n6_2, 'cell': 'Excel O218'}),
    ('davlenie_za_reshetkami_mpa_n5', {'fnc': calc_davlenie_za_reshetkami_mpa_n5, 'cell': 'Excel O209'}),
    ('y_n5', {'fnc': calc_y_n5, 'cell': 'Excel O210'}),
    ('n5', {'fnc': calc_n5, 'cell': 'Excel O212'}),
    ('n5_2', {'fnc': calc_n5_2, 'cell': 'Excel O213'}),
    ('n5_3', {'fnc': calc_n5_3, 'cell': 'Excel O214'}),
    ('perepad_davlenij_n5_2', {'fnc': calc_perepad_davlenij_n5_2, 'cell': 'Excel O211'}),
    ('davlenie_za_reshetkami_mpa_n4', {'fnc': calc_davlenie_za_reshetkami_mpa_n4, 'cell': 'Excel O202'}),
    ('y_n4', {'fnc': calc_y_n4, 'cell': 'Excel O203'}),
    ('n4', {'fnc': calc_n4, 'cell': 'Excel O205'}),
    ('n4_2', {'fnc': calc_n4_2, 'cell': 'Excel O206'}),
    ('n4_3', {'fnc': calc_n4_3, 'cell': 'Excel O207'}),
    ('perepad_davlenij_n4_2', {'fnc': calc_perepad_davlenij_n4_2, 'cell': 'Excel O204'}),
    ('davlenie_za_reshetkami_mpa_n3', {'fnc': calc_davlenie_za_reshetkami_mpa_n3, 'cell': 'Excel O195'}),
    ('y_n3', {'fnc': calc_y_n3, 'cell': 'Excel O196'}),
    ('n3', {'fnc': calc_n3, 'cell': 'Excel O198'}),
    ('n3_2', {'fnc': calc_n3_2, 'cell': 'Excel O199'}),
    ('n3_3', {'fnc': calc_n3_3, 'cell': 'Excel O200'}),
    ('perepad_davlenij_n3_2', {'fnc': calc_perepad_davlenij_n3_2, 'cell': 'Excel O197'}),
    ('davlenie_za_reshetkami_mpa_n2', {'fnc': calc_davlenie_za_reshetkami_mpa_n2, 'cell': 'Excel O188'}),
    ('y_n2', {'fnc': calc_y_n2, 'cell': 'Excel O189'}),
    ('n2', {'fnc': calc_n2, 'cell': 'Excel O191'}),
    ('n2_2', {'fnc': calc_n2_2, 'cell': 'Excel O192'}),
    ('n2_3', {'fnc': calc_n2_3, 'cell': 'Excel O193'}),
    ('perepad_davlenij_n2_2', {'fnc': calc_perepad_davlenij_n2_2, 'cell': 'Excel O190'}),
    ('davlenie_za_reshetkami_mpa_n1', {'fnc': calc_davlenie_za_reshetkami_mpa_n1, 'cell': 'Excel O181'}),
    ('y_n1', {'fnc': calc_y_n1, 'cell': 'Excel O182'}),
    ('n1', {'fnc': calc_n1, 'cell': 'Excel O184'}),
    ('n1_2', {'fnc': calc_n1_2, 'cell': 'Excel O185'}),
    ('n1_3', {'fnc': calc_n1_3, 'cell': 'Excel O186'}),
    ('perepad_davlenij_n1_2', {'fnc': calc_perepad_davlenij_n1_2, 'cell': 'Excel O183'}),
    ('davlenie_za_reshetkami_mpa_n0', {'fnc': calc_davlenie_za_reshetkami_mpa_n0, 'cell': 'Excel O174'}),
    ('y', {'fnc': calc_y, 'cell': 'Excel O15'}),
    ('λ', {'fnc': calc_λ, 'cell': 'Excel O16'}),
    ('v_aero', {'fnc': calc_v_aero, 'cell': 'Excel O269'}),
    ('dinamicheskaya_nagruzka_na_drosselnyj_blok_kn_2', {'fnc': calc_dinamicheskaya_nagruzka_na_drosselnyj_blok_kn_2, 'cell': 'Excel O304'}),
    ('dinamicheskaya_nagruzka_na_drosselnyj_blok_kn', {'fnc': calc_dinamicheskaya_nagruzka_na_drosselnyj_blok_kn, 'cell': 'Excel O170'}),
    ('dinamicheskaya_nagruzka_na_stupen_zvukopogloscheniya_kn_2', {'fnc': calc_dinamicheskaya_nagruzka_na_stupen_zvukopogloscheniya_kn_2, 'cell': 'Excel O305'}),
    ('dinamicheskaya_nagruzka_na_stupen_zvukopogloscheniya_kn', {'fnc': calc_dinamicheskaya_nagruzka_na_stupen_zvukopogloscheniya_kn, 'cell': 'Excel O171'}),
    ('davlenie_na_dnische_drosselnogo_bloka_mpa', {'fnc': calc_davlenie_na_dnische_drosselnogo_bloka_mpa, 'cell': 'Excel O308'}),
    ('f_dh_0_5_n6', {'fnc': calc_f_dh_0_5_n6, 'cell': 'Excel O391'}),
    # === ФИНАЛ ==='}),
    ('summ_diam', {'fnc': calc_summ_diam, 'cell': 'Excel O261'}),
    # === ПРОМЕЖУТОЧНЫЕ =='}),
    ('h_srednyaya_tolschina_plastin_m_n6', {'fnc': calc_h_srednyaya_tolschina_plastin_m_n6, 'cell': 'Excel O39'}),
    ('pd_skorostnoj_napor_na_vyhode_pa_n6', {'fnc': calc_pd_skorostnoj_napor_na_vyhode_pa_n6, 'cell': 'Excel O39'}),
    ('pd_srednij_skorostnoj_napor_na_vyhode_iz_schelevyh_kanalov', {'fnc': calc_pd_srednij_skorostnoj_napor_na_vyhode_iz_schelevyh_kanalov, 'cell': 'Excel O14'}),
    ('g_rashod_v_kanale_kg_s_n6', {'fnc': calc_g_rashod_v_kanale_kg_s_n6, 'cell': 'Excel O39'}),
    ('w_skorost_v_kanale_m_s_n6', {'fnc': calc_w_skorost_v_kanale_m_s_n6, 'cell': 'Excel O39'}),
    ('maksimalnaya_skorost_mezhdu_kasset_m_s', {'fnc': calc_maksimalnaya_skorost_mezhdu_kasset_m_s, 'cell': 'Excel O26'}),
    ('m_chislo_maha_v_kanale_n6', {'fnc': calc_m_chislo_maha_v_kanale_n6, 'cell': 'Excel O39'}),
    ('k_m_n6', {'fnc': calc_k_m_n6, 'cell': 'Excel O39'}),
    ('ds_n6', {'fnc': calc_ds_n6, 'cell': 'Excel O39'}),
    ('ws_moschnost_shuma_na_vyhode_kanala_vt_n6', {'fnc': calc_ws_moschnost_shuma_na_vyhode_kanala_vt_n6, 'cell': 'Excel O39'}),
    ('lws_n6', {'fnc': calc_lws_n6, 'cell': 'Excel O40'})
])

