# -*- coding: utf-8 -*-
"""Входные параметры для расчёта пневмотранспорта ПКН.
Собрано по листу «Пневмотранспорт ПКН» из Excel-модели.
Поле H14 («Фактический принятый») вынесено в левую часть отдельной группой.
"""

list_dicts_data_input = [{'name': 'pump_volume_m3',
  'header': 'Объем насоса',
  'val': 15.0,
  'dimension': 'м3',
  'min_max_list': (1e-06, 1000000.0),
  'default_val': 15.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'purge_time_sec',
  'header': 'Время продувки насоса',
  'val': 5.0,
  'dimension': 'сек',
  'min_max_list': (0.0, 1000000.0),
  'default_val': 5.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'loading_time_sec',
  'header': 'Время загрузки насоса',
  'val': 600.0,
  'dimension': 'сек',
  'min_max_list': (0.0, 1000000.0),
  'default_val': 600.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'load_time_sec',
  'header': 'Время нагрузки',
  'val': 10.0,
  'dimension': 'сек',
  'min_max_list': (0.0, 1000000.0),
  'default_val': 10.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 # {'name': 'unloading_time_sec',
 #  'header': 'Время разгрузки',
 #  'val': 430.5128140520374,
 #  'dimension': 'сек',
 #  'min_max_list': None,
 #  'default_val': 430.5128140520374,
 #  'data_type': 'float',
 #  'comment': 'Рассчитывается автоматически',
 #  'accuracy': 2,
 #  'group_name': 'Параметры системы',
 #  'editable': False},
 {'name': 'waiting_time_sec',
  'header': 'Остальное время ожидания',
  'val': 1.0,
  'dimension': 'сек',
  'min_max_list': (0.0, 1000000.0),
  'default_val': 1.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'particle_size_mm',
  'header': 'Средний размер частиц',
  'val': 0.05,
  'dimension': 'мм',
  'min_max_list': (1e-06, 10000.0),
  'default_val': 0.05,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'material_density_kg_m3',
  'header': 'Плотность материала',
  'val': 1200.0,
  'dimension': 'кг/м3',
  'min_max_list': (1e-06, 1000000.0),
  'default_val': 1200.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'bulk_density_kg_m3',
  'header': 'Насыпная плотность',
  'val': 1000.0,
  'dimension': 'кг/м3',
  'min_max_list': (1e-06, 1000000.0),
  'default_val': 1000.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 {'name': 'system_temp_c',
  'header': 'Температура системы Тсист.',
  'val': 80.0,
  'dimension': 'С',
  'min_max_list': None,
  'default_val': 80.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры системы',
  'editable': True},
 # {'name': 'system_temp_k',
 #  'header': 'Температура системы',
 #  'val': 353.0,
 #  'dimension': 'К',
 #  'min_max_list': None,
 #  'default_val': 353.0,
 #  'data_type': 'float',
 #  'comment': 'Рассчитывается автоматически',
 #  'accuracy': 2,
 #  'group_name': 'Параметры системы',
 #  'editable': False},
 # {'name': 'gas_constant_j_kg_k',
 #  'header': 'Газовая постоянная',
 #  'val': 287.0,
 #  'dimension': 'Дж/кг*К',
 #  'min_max_list': None,
 #  'default_val': 287.0,
 #  'data_type': 'float',
 #  'comment': 'Справочное значение для методики ПКН',
 #  'accuracy': 2,
 #  'group_name': 'Параметры системы',
 #  'editable': False},
 # {'name': 'dynamic_viscosity_pa_s',
 #  'header': 'Динамическая вязкость при Тсист.',
 #  'val': 2.0867169925616006e-05,
 #  'dimension': 'Па*с',
 #  'min_max_list': None,
 #  'default_val': 2.0867169925616006e-05,
 #  'data_type': 'float',
 #  'comment': 'Рассчитывается автоматически',
 #  'accuracy': 12,
 #  'group_name': 'Параметры системы',
 #  'editable': False},
 {'name': 'horizontal_pipe_length_m',
  'header': 'Длина  горизонтального трубопровода',
  'val': 620.0,
  'dimension': 'м',
  'min_max_list': (1e-06, 1000000.0),
  'default_val': 620.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'vertical_pipe_length_m',
  'header': 'Длина вертикального участка',
  'val': 40.0,
  'dimension': 'м',
  'min_max_list': (0.0, 1000000.0),
  'default_val': 40.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'system_ash_flow_kg_h',
  'header': 'Расход золы системы',
  'val': 116000.0,
  'dimension': 'кг/ч',
  'min_max_list': (1e-06, 100000000.0),
  'default_val': 116000.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'gravity_m_s2',
  'header': 'Ускорение свободного падения',
  'val': 9.81,
  'dimension': 'м/с2',
  'min_max_list': (1e-06, 1000.0),
  'default_val': 9.81,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'mass_concentration_kg_kg',
  'header': 'Массовая концентрация ',
  'val': 16.0,
  'dimension': 'кг/кг',
  'min_max_list': (1e-06, 1000000.0),
  'default_val': 16.0,
  'data_type': 'float',
  'comment': 'При необходимости откройте рисунок-подсказку и скорректируйте значение вручную.',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 # {'name': 'air_density_kg_m3',
 #  'header': 'Плотность воздуха при Тсист.',
 #  'val': 1.0005303522302051,
 #  'dimension': 'кг/м3',
 #  'min_max_list': None,
 #  'default_val': 1.0005303522302051,
 #  'data_type': 'float',
 #  'comment': 'Рассчитывается автоматически',
 #  'accuracy': 12,
 #  'group_name': 'Параметры трассы',
 #  'editable': False},
 {'name': 'outlet_air_velocity_m_s',
  'header': 'Скорость воздуха на выходе системы',
  'val': 40.0,
  'dimension': 'м/с',
  'min_max_list': (1e-06, 1000000.0),
  'default_val': 40.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'turns_90_count',
  'header': 'Количество поворотов трассы 90гр.',
  'val': 5,
  'dimension': 'шт.',
  'min_max_list': (0, 10000),
  'default_val': 5,
  'data_type': 'int',
  'comment': '',
  'accuracy': 0,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'turns_60_count',
  'header': 'Количество поворотов трассы 60гр.',
  'val': 1,
  'dimension': 'шт.',
  'min_max_list': (0, 10000),
  'default_val': 1,
  'data_type': 'int',
  'comment': '',
  'accuracy': 0,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'turns_30_count',
  'header': 'Количество поворотов трассы 30гр.',
  'val': 1,
  'dimension': 'шт.',
  'min_max_list': (0, 10000),
  'default_val': 1,
  'data_type': 'int',
  'comment': '',
  'accuracy': 0,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'flow_switches_count',
  'header': 'Количество переключателей потока на трассе',
  'val': 3,
  'dimension': 'шт.',
  'min_max_list': (0, 10000),
  'default_val': 3,
  'data_type': 'int',
  'comment': '',
  'accuracy': 0,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'compressor_and_airline_losses_bar',
  'header': 'Потери давления в компрессоре и воздухопроводе',
  'val': 0.1,
  'dimension': 'кг/см2',
  'min_max_list': (0.0, 1000000.0),
  'default_val': 0.1,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'atmospheric_pressure_pa',
  'header': 'Атмосферное давление',
  'val': 101325.0,
  'dimension': 'Па',
  'min_max_list': (1e-06, 1000000000.0),
  'default_val': 101325.0,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 {'name': 'safety_factor',
  'header': 'Коэффициент запаса',
  'val': 1.1,
  'dimension': '',
  'min_max_list': (1e-06, 1000.0),
  'default_val': 1.1,
  'data_type': 'float',
  'comment': '',
  'accuracy': 2,
  'group_name': 'Параметры трассы',
  'editable': True},
 # {'name': 'kinematic_viscosity_m2_s',
 #  'header': 'Кинематическая вязкость газа',
 #  'val': 2.085610884177837e-05,
 #  'dimension': 'м2/с',
 #  'min_max_list': None,
 #  'default_val': 2.085610884177837e-05,
 #  'data_type': 'float',
 #  'comment': 'Рассчитывается автоматически',
 #  'accuracy': 12,
 #  'group_name': 'Параметры трассы',
 #  'editable': False},
 {'name': 'actual_diameter_m',
  'header': 'Фактический принятый',
  'val': 0.257,
  'dimension': 'м',
  'min_max_list': (1e-06, 1000.0),
  'default_val': 0.257,
  'data_type': 'float',
  'comment': 'Параметр для ручной итерации после просмотра подсказки.',
  'accuracy': 2,
  'group_name': 'Корректируемые после расчета',
  'editable': True}]
