# -*- coding: utf-8 -*-
"""Входные параметры для модуля акустических расчётов.
Автоматически сгенерировано из листа «Акустика» файла «Расчет ШГ рев6_mod.xlsm».
Не редактируйте вручную: при изменении Excel перегенерируйте модуль.
"""


list_dicts_data_input = [
    {'name': 'ak_skorost_protekaniya_sredi_mejdu_plastinami', 'header': 'Скорость протекания среды между пластинами', 'val': '40 м/с', 'dimension': 'м/с', 'min_max_list': ["10 м/с", "15 м/с", "20 м/с", "25 м/с", "30 м/с", "35 м/с", "40 м/с"], 'default_val': "40 м/с", 'data_type': 'str', 'comment': '', 'accuracy': 3, 'group_name': 'РАСЧЕТЫ АКУСТИКИ:'},
    {'name': 'ak_tolschina_plastin_rasstoyanie_mezhdu_plastinami', 'header': 'Толщина пластин/Расстояние между пластинами', 'val': '100/100 (v<30)', 'dimension': '', 'min_max_list': ["50/50", "100/100 (v<15)", "100/100 (v<20)", "100/100 (v<30)", "200/200 (v<15)", "200/200 (v<20)", "200/200 (v<30)", "200/400"], 'default_val': '100/100 (v<30)', 'data_type': 'str', 'comment': 'Плотность 100 кг/м3', 'accuracy': 3, 'group_name': 'Плотность 100 кг/м3'},
    {'name': 'ak_izdavaemyj_shum', 'header': 'Издаваемый шум', 'val': 'Продувка', 'dimension': '', 'min_max_list': ["Продувка", "Пред. клапан" ], 'default_val': 'Продувка', 'data_type': 'str', 'comment': 'Параметры среды', 'accuracy': 3, 'group_name': 'Параметры среды'},
    {'name': 'ak_tip_klapana', 'header': 'Тип клапана', 'val': 'Чашечный', 'dimension': '', 'min_max_list': ["Чашечный", "Поворотный" ], 'default_val': 'Чашечный', 'data_type': 'str', 'comment': '', 'accuracy': 3, 'group_name': 'Параметры среды'},
    {'name': 'ak_produvka_vnutrennij_diametr_truby_m_du_klapana_m', 'header': 'Продувка / Внутренний диаметр трубы, м / Ду клапана, м', 'val': 0.2, 'dimension': 'м', 'min_max_list': '', 'default_val': 0.2, 'data_type': 'float', 'comment': '', 'accuracy': 3, 'group_name': 'Параметры среды'},
    {'name': 'ak_produvka_davlenie_v_nachale_truby_mpa_davlenie_do_klapana_mpa', 'header': 'Давление в начале трубы, МПа / Давление до клапана, МПа', 'val': 13.5, 'dimension': 'МПа', 'min_max_list': '', 'default_val': 13.5, 'data_type': 'float', 'comment': '', 'accuracy': 3, 'group_name': 'Параметры среды'},
    {'name': 'ak_produvka_atmosfernoe_davlenie_mpa_davlenie_posle_klapana_mpa', 'header': 'Атмосферное давление, МПа / Давление после клапана, МПа', 'val': 0.1, 'dimension': 'МПа', 'min_max_list': '', 'default_val': 0.1, 'data_type': 'float', 'comment': '', 'accuracy': 3, 'group_name': 'Параметры среды'},
    {'name': 'ak_proekciya_rasstoyaniya_ot_istochnika_shuma_do_priemnika_na_ploskost_zemli_m', 'header': 'Проекция расстояния от источника шума до приемника на плоскость земли, м', 'val': 1, 'dimension': 'м', 'min_max_list': '', 'default_val': 1, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Расчет затухания в атмосфере'},
    {'name': 'ak_kategoriya_poverhnosti', 'header': 'Категория поверхности', 'val': 'Твердая (Асфальт, бетон, …)', 'dimension': '', 'min_max_list': ["Твердая (Асфальт, бетон, …)", "Пористая(Земля, трава, …)", "Смешаная"], 'default_val': 'Твердая (Асфальт, бетон, …)', 'data_type': 'str', 'comment': 'Расчет затухания в атмосфере', 'accuracy': 3, 'group_name': 'Расчет затухания в атмосфере', 'visible': False},
    {'name': 'ak_uroven_zvuka_dba_pdu_po_sn2_2_4_2_1_2_562_96_db', 'header': 'Уровень звука, дБа ПДУ по СН2.2.4/2.1.2.562-96, дБ', 'val': 85, 'dimension': 'дБ', 'min_max_list': ["85", "80", "75", "70", "65", "60", "55", "50"], 'default_val': 85, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Определение УЗД в расчетной точке при установке шумоглушителя', 'visible': False},
    {'name': 'ak_uroven_zvuka_dba_raschetnye_pdu_po_sn2_2_4_2_1_2_562_96_db', 'header': 'Уровень звука, дБа (Расчетные) ПДУ по СН2.2.4/2.1.2.562-96, дБ', 'val': 80, 'dimension': 'дБ', 'min_max_list': ["110", "85", "80", "75"], 'default_val': 80, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Определение УЗД в расчетной точке при установке шумоглушителя', 'visible': False},
    {'name': 'ak_vysota_istochnika_shuma_nad_zemlej_m', 'header': 'Высота источника шума над землей, м', 'val': 2, 'dimension': 'м', 'min_max_list': '', 'default_val': 2, 'data_type': 'int', 'comment': 'ВЗЯТЬ ПО УМОЛЧАНИЮ - 2 м на каждой ячейке', 'accuracy': 3, 'group_name': 'Определение УЗД в расчетной точке при установке шумоглушителя', 'visible': False},
    {'name': 'ak_vysota_priemnika_nad_zemlej_m', 'header': 'Высота приемника над землей, м', 'val': 2, 'dimension': 'м', 'min_max_list': '', 'default_val': 2, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Определение УЗД в расчетной точке при установке шумоглушителя', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 31,5', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_2', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 63', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_3', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 125', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_4', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 250', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_5', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 500', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_6', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 1000', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_7', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 2000', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_8', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 4000', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_9', 'header': 'Фоновый шум, дБ Среднегеометрическая частота, Гц 8000', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
    {'name': 'ak_fonovyj_shum_db_srednegeometricheskaya_chastota_gc_31_5_10', 'header': 'Уровень звука', 'val': 0, 'dimension': 'дБ', 'min_max_list': '', 'default_val': 0, 'data_type': 'int', 'comment': '', 'accuracy': 3, 'group_name': 'Фоновый шум', 'visible': False},
]
