# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\a.belyakov\AppData\Local\Programs\Python\Python312\project_cust_38\sub_mes\manual_mngr\manual_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(948, 739)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(8)
        self.splitter.setObjectName("splitter")
        self.fr_view = QtWidgets.QFrame(self.splitter)
        self.fr_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_view.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_view.setObjectName("fr_view")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.fr_view)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.txtbr_view = QtWidgets.QTextBrowser(self.fr_view)
        self.txtbr_view.setObjectName("txtbr_view")
        self.verticalLayout.addWidget(self.txtbr_view)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_edit_last = QtWidgets.QPushButton(self.fr_view)
        self.btn_edit_last.setObjectName("btn_edit_last")
        self.horizontalLayout.addWidget(self.btn_edit_last)
        self.btn_edit_current = QtWidgets.QPushButton(self.fr_view)
        self.btn_edit_current.setObjectName("btn_edit_current")
        self.horizontalLayout.addWidget(self.btn_edit_current)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.fr_history = QtWidgets.QFrame(self.splitter)
        self.fr_history.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_history.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_history.setObjectName("fr_history")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.fr_history)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tbl_history = QtWidgets.QTableWidget(self.fr_history)
        self.tbl_history.setObjectName("tbl_history")
        self.tbl_history.setColumnCount(0)
        self.tbl_history.setRowCount(0)
        self.verticalLayout_2.addWidget(self.tbl_history)
        self.verticalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 948, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_edit_last.setText(_translate("MainWindow", "Изменить актуальную"))
        self.btn_edit_current.setText(_translate("MainWindow", "Изменить выбранную"))
